### ISSUE TITLE
Detect WSL **1** processes

### ISSUE THREAD

**Issue by LoganDark** [safing/portmaster#1135]
**What would you like to add or change?**:
Portmaster currently counts WSL **1** processes as "Other Connections", but these processes are detectable individually by Windows Firewall, and even identifiable by distro & path inside the distro.

Even though WSL 2 runs in a virtual machine, so you can only detect network access by the entire virtual machine, WSL 1 runs directly under the Windows kernel and therefore has separate processes with their own PIDs and metadata that should be able to be identified by Portmaster.

**Why do you and others need this?**:
"Other Connections" is essentially all-or-nothing right now and this would probably be the easiest way to get at least some WSL support in.

**Comment by Raphty** [comment]
Virtualizations in general are something we are not working on at the moment, but want to tackle in the future.

**Comment by dhaavi** [comment]
> actual separate processes under the Windows kernel

Do you have more information on that? From what I can tell, if that were the case, then it should work, as we just use the PID that Windows reports for a connection and then have Windows give us more info on that PID. So, if it were just normal processes, everything should be working already.

My guess is that the Task Manager and ProcessHacker have built in special support.

What do you see when you click on "Process Details" on a connection from WSL1 in Portmaster?

**Comment by LoganDark** [comment]
> My guess is that the Task Manager and ProcessHacker have built in special support.

They don't. They have their own PIDs.

![image](https://user-images.githubusercontent.com/4723091/228539948-68ee9634-bc2f-42bd-a866-ca238c755b2c.png)

> From what I can tell, if that were the case, then it should work, as we just use the PID that Windows reports for a connection and then have Windows give us more info on that PID. So, if it were just normal processes, everything should be working already.

![image](https://user-images.githubusercontent.com/4723091/228541186-add2021f-8f80-4eb8-b26a-cdea907f57f0.png)

![image](https://user-images.githubusercontent.com/4723091/228541497-5ee190d2-c340-413e-912f-f1dbf134d7a5.png)

![image](https://user-images.githubusercontent.com/4723091/228541541-8d929e4d-ced3-41ac-afd8-8bd40fc363c0.png)

Windows Defender Firewall can tell WSL1 processes apart, Task Manager and Process Hacker can, even tasklist can tell

```
C:\Users\LoganDark>tasklist | findstr fish
fish                         24880 Console                    1      6,064 K
```

I don't know what more proof you need that this is a real process with a real PID, not to mention that killing the process from Windows works:

![image](https://user-images.githubusercontent.com/4723091/228542072-25a6b6e5-7e22-430b-a645-e272c8d7fbc6.png)

This is **not** like WSL2 which **is** just a VM—I can't show it in Portmaster because *Portmaster actually completely freaking ignores all its connections so I cannot even filter domains for the entire WSL2 VM* but here is the WSL2 VM:

![image](https://user-images.githubusercontent.com/4723091/228543266-fa01e7ec-dac7-4525-b36b-4d8b07db0516.png)

> What do you see when you click on "Process Details" on a connection from WSL1 in Portmaster?

oop, that's above.

**Comment by LoganDark** [comment]
Here is a non-ICMP request, by the way:

![image](https://user-images.githubusercontent.com/4723091/231179864-bcf8c44b-888d-4836-9cdc-c3396d4567f1.png)

Portmaster detects it and logs it and even filters it correctly, it just doesn't know where it came from.

But if I fire up Windows Firewall Control and take a look at the Windows Firewall logs, here is the DNS request performed by `curl`:

![image](https://user-images.githubusercontent.com/4723091/231180507-6e056f27-03bf-4282-934d-e3739c0dd046.png)

Well hey, would you look at that~

**Comment by Terrance** [comment]
The [latest blog post](https://safing.io/blog/2023/08/08/portmaster-v1.3/#better-process-detection) notes:

> ### Better Process Detection
> 
> Portmaster used to regularly have “Other Connections”. These were connections Portmaster was not able to attribute to a process. We improved the system integration on both Linux (via eBPF) and Windows (via our kernel driver) in order to get higher quality data about the connections. This means that you normally should not see any connections in the “Other Connections” app anymore. In our tests, every single connection was attributed correctly!

For the record, I'm still seeing WSL 1 processes being attributed to _Other Connections_ in Portmaster 1.3.6.

**Comment by Raphty** [comment]
@Terrance VM's are and has been not supported officially. some VM software does work but others don't.
https://wiki.safing.io/en/FAQ/VMsAndPortmaster

**Comment by Terrance** [comment]
I'm aware of the limited support for virtualisation, but I'm also commenting on this issue where, as described above, WSL1 is not a virtualisation layer in that sense.  The blog post saying "you normally should not see any [other] connections" seemed strong enough to warrant providing an update, in case anything has changed since the last response in here.

**Comment by LoganDark** [comment]
@Rapthy WSL 1 is not a virtual machine. WSL 1 is a different system call ABI provided directly by the Windows kernel and does not rely on Hyper-V or any other virtualization components. It's basically just a different type of process.

**Comment by LoganDark** [comment]
Closing as portmaster no longer prioritizes free features
